apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hello-world
  namespace: hello-world
spec:
  rules:
  - host: bill-gas-demo.eng.rancher.space
    http:
      paths:
      - backend:
          serviceName: hello-world
          servicePort: 80
        pathType: ImplementationSpecific
