apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hello-world-ing
spec:
  rules:
  - host: fleet-managed-downstream.local
    http:
      paths:
      - pathType: Prefix 
        path: "/"
        backend:
          serviceName: hello-world-svc
          servicePort: 80
